### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by aabbtree77** [mudler/edgevpn#137]
I have been running this successfully continuously with the debug option for days:

sudo IFACE=edgevpn0 ADDRESS=x.x.x.x/24 EDGEVPNCONFIG=config.yaml ./edgevpn --log-level debug

until it hung up (I could not longer connect to the machine with the virtual EdgeVPN IP x.x.x.x./24 which has some concrete numbers that I do not show here).

Please take a look at the last five lines of the log which I include here with some more data:

...
{"level":"DEBUG","time":"2023-07-15T03:49:57.400+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooW9tLGq2fPXsuqJ3YzafeE6XaMarXTSahFD5azDHcDEz92'\n"}
{"level":"DEBUG","time":"2023-07-15T03:49:57.401+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWBLgGUYiye8ek3iUiThpHKMuxQYo7jwP4A6Nez5v7kZSn'\n"}
{"level":"DEBUG","time":"2023-07-15T03:57:26.742+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T03:57:28.292+0300","caller":"discovery/dht.go:147","message":" failed to dial QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ:\n  * [/ip4/127.0.0.1/tcp/4001] dial tcp4 127.0.0.1:4001: connect: connection refused\n  * [/ip4/104.131.131.82/tcp/4001] dial tcp4 0.0.0.0:42139->104.131.131.82:4001: i/o timeout\n  * [/ip4/127.0.0.1/udp/4001/quic-v1] timeout: no recent network activity\n  * [/ip4/104.131.131.82/udp/4001/quic-v1] timeout: no recent network activity"}
{"level":"DEBUG","time":"2023-07-15T03:57:32.850+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T03:57:36.029+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T03:57:36.514+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T03:57:36.514+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T03:57:48.053+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWK6wseoeHMMzjk5ZhtsgfcVBMxo1H9cQ9A5adDjfBKX7v'\n"}
{"level":"DEBUG","time":"2023-07-15T03:57:48.053+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWBLgGUYiye8ek3iUiThpHKMuxQYo7jwP4A6Nez5v7kZSn'\n"}

...

{"level":"DEBUG","time":"2023-07-15T03:57:48.054+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWBN6wj7NLoqFj6qkxm7EWwxVacfiQBv1NEmdVFU4ZKsV7'\n"}
{"level":"DEBUG","time":"2023-07-15T03:59:26.553+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T03:59:26.553+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T03:59:57.336+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:00:01.982+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:00:01.982+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:05:29.029+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:05:29.177+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:05:29.327+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:05:29.491+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:05:29.491+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:05:35.070+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:05:35.070+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:05:36.929+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:05:39.241+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:05:39.241+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:15:04.867+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:15:05.055+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:15:08.988+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:15:10.254+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:15:10.254+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:15:16.665+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:15:16.665+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:15:19.447+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:15:26.963+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:15:26.963+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:25:48.965+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:25:49.016+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}"}
{"level":"DEBUG","time":"2023-07-15T04:25:49.100+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:25:55.440+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:25:55.441+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:25:59.036+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:25:59.036+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:26:00.131+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:26:06.616+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:26:06.616+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:28:43.172+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWLT8rpjX9Em3Rzup5jaRoajvJMi6ZAUzMcmKDpUXyvzcs'\n"}
{"level":"DEBUG","time":"2023-07-15T04:28:43.172+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWKZe2tqXYA6bYToTa2QtAJ6Pq5xUGLtHwFAbQSf6rNVWy'\n"}

...

{"level":"DEBUG","time":"2023-07-15T04:28:43.173+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWLbVkx1SPNQXv5HzXGYNYxGvbwC9qyDtqPWJFqo48gW1d'\n"}
{"level":"DEBUG","time":"2023-07-15T04:33:51.004+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:33:51.198+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:33:51.472+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:33:51.514+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:33:52.330+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}"}
{"level":"DEBUG","time":"2023-07-15T04:33:52.330+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:33:54.977+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:33:54.977+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:33:56.104+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:33:58.776+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:33:58.776+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:50:05.117+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ: [/ip4/104.131.131.82/tcp/4001]}"}
{"level":"DEBUG","time":"2023-07-15T04:50:10.235+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:50:15.193+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:50:19.413+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:50:19.778+0300","caller":"discovery/dht.go:149","message":" Connection established with bootstrap node: {QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt: [/dnsaddr/bootstrap.libp2p.io]}"}
{"level":"DEBUG","time":"2023-07-15T04:50:19.778+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:50:24.420+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:50:24.420+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:50:55.040+0300","caller":"discovery/dht.go:204","message":" Announcing ourselves..."}
{"level":"DEBUG","time":"2023-07-15T04:51:25.068+0300","caller":"discovery/dht.go:207","message":" Successfully announced!"}
{"level":"DEBUG","time":"2023-07-15T04:51:25.068+0300","caller":"discovery/dht.go:210","message":" Searching for other peers..."}
{"level":"DEBUG","time":"2023-07-15T04:52:20.820+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWLT8rpjX9Em3Rzup5jaRoajvJMi6ZAUzMcmKDpUXyvzcs'\n"}

...

{"level":"DEBUG","time":"2023-07-15T04:52:20.821+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooW9tLGq2fPXsuqJ3YzafeE6XaMarXTSahFD5azDHcDEz92'\n"}
{"level":"DEBUG","time":"2023-07-15T04:52:20.821+0300","caller":"discovery/dht.go:175","message":"[relay discovery] Found close peer '12D3KooWBLgGUYiye8ek3iUiThpHKMuxQYo7jwP4A6Nez5v7kZSn'\n"}
panic: close of closed channel

goroutine 1739780 [running]:
github.com/mudler/edgevpn/pkg/discovery.(*DHT).FindClosePeers.func1.1()
	/home/runner/work/edgevpn/edgevpn/pkg/discovery/dht.go:196 +0x1a8
created by github.com/mudler/edgevpn/pkg/discovery.(*DHT).FindClosePeers.func1
	/home/runner/work/edgevpn/edgevpn/pkg/discovery/dht.go:160 +0x173

The halting occurred on about third day, after restarting it all works again. I suspect it will be nearly impossible to reproduce this issue, but letting you know that this might not be a bullet proof code for long runs yet. 

This edgevpn instance runs on the Ubuntu laptop, it does not look like the cause could have been some "suspend regime" or anything like that, but I am not 100% sure. 

I will add here more information if I get this error again.

**Comment by aabbtree77** [comment]
The error persists whenever edgevpn runs longer, say for two hours. After that the VPN connection gets lost and there is no way to reconnect to this Ubuntu 22.04 remote machine anymore. 

We are now testing [awl](https://github.com/anywherelan/awl) which also relies on go-libp2p, to see if this is something specific to the EdgeVPN code base.

These reports could also be relevant:

https://github.com/cloudflare/cloudflared/issues/1007

https://devsday.ru/blog/details/66786
