### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by neuthral** [mudler/edgevpn#371]
this happends on Ubuntu 22.04 after 10 seconds of running
```sh
panic: send on closed channel

goroutine 7500 [running]:
github.com/mudler/edgevpn/pkg/config.Config.ToOpts.(*DHT).FindClosePeers.func28.1()
        /home/runner/work/edgevpn/edgevpn/pkg/discovery/dht.go:193 +0x6a5
created by github.com/mudler/edgevpn/pkg/config.Config.ToOpts.(*DHT).FindClosePeers.func28 in goroutine 7497
        /home/runner/work/edgevpn/edgevpn/pkg/discovery/dht.go:160 +0x137
```

**Comment by brucel11qwe** [comment]
This is because it is unable to connect to the relay or bootstrapt
