### ISSUE TITLE
panic with DHCP

### ISSUE THREAD

**Issue by dukzcry** [mudler/edgevpn#38]
Hi @mudler!
I have an issue I see randomly on peers when using DHCP feature
```
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: {"level":"DEBUG","time":"2022-11-26T14:22:35.984+0300","caller":"vpn/dhcp.go:83","message":"12D3KooWBVp3ogQY8itAbmJCLuDt8vaoCMwf8QVetUB4ZAEmPCPP uses 10.0.1.1\n"}
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: {"level":"DEBUG","time":"2022-11-26T14:22:35.984+0300","caller":"vpn/dhcp.go:83","message":"12D3KooWNVqBVGt63AUq6VoVQZ1hTTdZ7MYyqDAkgGVmEPBoqidG uses 10.0.1.2\n"}
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: panic: runtime error: index out of range [0] with length 0
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: goroutine 1 [running]:
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/mudler/edgevpn/pkg/utils.Leader({0x285f638, 0x0, 0xc003d256c0?})
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/mudler/edgevpn/pkg/utils/leader.go:28 +0x1a5
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/mudler/edgevpn/pkg/vpn.DHCPNetworkService.func1({_, _}, {{0xc00081c3c0, 0x20}, {0xc00081c460, 0x20}, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/mudler/edgevpn/pkg/vpn/dhcp.go:99 +0x356
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/mudler/edgevpn/pkg/node.(*Node).Start(0xc000aa0000, {0x17cbf70, 0xc0000443e0})
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/mudler/edgevpn/pkg/node/node.go:131 +0x2ba
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/mudler/edgevpn/cmd.Main.func1(0xc000856160)
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/mudler/edgevpn/cmd/main.go:221 +0xfae
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/urfave/cli.HandleAction({0x1098d20?, 0x1635ab8?}, 0xc000840540?)
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/urfave/cli@v1.22.10/app.go:524 +0xa8
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: github.com/urfave/cli.(*App).Run(0xc000840540, {0xc00003c180, 0x3, 0x3})
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/urfave/cli@v1.22.10/app.go:286 +0x7d9
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]: main.main()
ноя 26 14:22:35 si-ni-tsin jajykimzibnqvw4b7qwjmxmh8b2142lk-edgevpn[197342]:         github.com/mudler/edgevpn/main.go:52 +0x785
ноя 26 14:22:36 si-ni-tsin systemd[1]: edgevpn.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
ноя 26 14:22:36 si-ni-tsin systemd[1]: edgevpn.service: Failed with result 'exit-code'.
ноя 26 14:22:36 si-ni-tsin systemd[1]: edgevpn.service: Consumed 13.334s CPU time, received 6.0M IP traffic, sent 13.4M IP traffic.
```

**Comment by mudler** [comment]
Hey @dukzcry ! 

Ouch, that should not happen, fixing it - thanks for the heads up!

**Comment by dukzcry** [comment]
@mudler Works great, thank you!

**Comment by mudler** [comment]
Awesome! Thank you for the quick feedback!
